# Config (MicroProfile Config)
payment.timeout=1000
payment.gateway.simulate-failures=0

# REST Client (MicroProfile REST Client)
quarkus.rest-client.payment-gateway.url=http://127.0.0.1:8080

# OpenAPI
quarkus.smallrye-openapi.path=/q/openapi
