# MicroProfile server
server.port=8081
server.host=0.0.0.0

# Config (MicroProfile Config)
payment.timeout=1000
payment.gateway.simulate-failures=0

# REST Client (MicroProfile REST Client)
payment-gateway/mp-rest/url=http://127.0.0.1:8081

# Metrics (disabled for simplicity)
metrics.rest-request.enabled=false
