apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-svc"
spec:
  selector:
    app: {{ .Values.name }}
  type: NodePort
  ports:
    - name: "{{ .Values.name }}-svc-port"
      port: {{ .Values.port }}
      targetPort: db-port